#!/usr/bin/sh
# Copyright (C) 2018 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

#PBS -l select=1:ncpus=2:mpiprocs=1
#PBS -l walltime=0:0:40
#PBS -A DonsAccount
#PBS -j oe
pbsdsh -- sleep 3600
