#!/usr/bin/sh
# Copyright (C) 2018 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

#PBS -l select=4:ncpus=2:mpiprocs=1
#PBS -l walltime=1:00:00
#PBS -A ToddsAccount
#PBS -j oe
pbsdsh -- ~/dai/UMT 1
pbsdsh -- ~/dai/MILC 1
pbsdsh -- ~/dai/NEKbone 1
