#!/bin/bash
#
# Copyright (C) 2018 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

cd ~/dai/clients
#
echo "Starting to submit the jobs"
java zzProcess19kJobs ~/dai/save-Pbs-19K-Jobs-template /tmp/InputForAdapterWlm1.log
#
