#!/bin/bash
# Copyright (C) 2018 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

#
#SBATCH -N 64
srun /opt/ucs/demo/workloads/AMG 1
srun /opt/ucs/demo/workloads/dgemm 2
srun /opt/ucs/demo/workloads/linpak 3
srun /opt/ucs/demo/workloads/MILC 4
srun /opt/ucs/demo/workloads/mpibench 5
srun /opt/ucs/demo/workloads/NEKbone 6
srun /opt/ucs/demo/workloads/qcd 7
srun /opt/ucs/demo/workloads/stress 8
srun /opt/ucs/demo/workloads/UMT 9