dai-json-server:
  image: vimagick/json-server
  container_name: dai-json-server
#  command: --id ID --host 0.0.0.0 --watch inventory.db.json --routes routes.json
  command: --id ID --host 0.0.0.0 --watch eventsim.inventory.db.json --routes routes.json
  ports:
    - 3000:3000
  volumes:
    - .:/data
