#!/bin/bash
################################################################################
# Example environment variables that Slurm will fill in before invocation.
################################################################################
### SLURM_NODELIST=n[000000-000001]
### SLURMD_NODENAME=n000001
### SLURM_JOBID=636
### SLURM_STEP_ID=0
### SLURM_CONF=/etc/slurm/slurm.conf
### SLURM_JOB_ID=636
### PWD=/var/log
### SLURM_JOB_USER=ddreed
### SLURM_UID=1000
### SLURM_JOB_UID=1000
### SHLVL=1
### SLURM_CLUSTER_NAME=linux
### SLURM_JOB_PARTITION=vDudley
### SLURM_JOB_CONSTRAINTS=(null)  OR  SLURM_JOB_CONSTRAINTS=ENV_Capability  OR SLURM_JOB_CONSTRAINTS=ENV_Rich etc.
### _=/usr/bin/printenv
################################################################################
#
# Issue command so that this script logs into a file (for debug purposes).
exec >> /tmp/Prolog-Job$SLURM_JOB_ID.log 2>&1
#
echo "$(TZ=UTC date +%Y-%m-%dT%H:%M:%S.%N) Prolog - started - Job ID=$SLURM_JOBID, Job Constraints='$SLURM_JOB_CONSTRAINTS', Node Name='$SLURMD_NODENAME'"
#
###echo ""
###printenv
###echo ""
#
# Create a file in the directory that we use in order to tell which jobs are currently active on this node, simple existence of the file indicates that the job is active on this node.
ActiveJobDirectory=/etc/slurm/UcsActiveJobsOnThisNode
mkdir -p "$ActiveJobDirectory"
echo "$(TZ=UTC date +%Y-%m-%dT%H:%M:%S.%N) Prolog - creating file in the active jobs directory, so that we know this job is now active on this node - touch $ActiveJobDirectory/$SLURM_JOB_ID"
touch "$ActiveJobDirectory"/$SLURM_JOB_ID
#
# Note: we do not need to put this node's UCS location string (lctn) into the mOS repository!
#   As Todd is going to take care of this in the UCS early boot script, by writing the node's lctn into /sys/kernel/mOS/ras/location
#
# Put the list of active jobs for this node into the mOS repository.
for j in /etc/slurm/UcsActiveJobsOnThisNode/*; do
    j=${j##*/}
    if [[ $j != '*' ]]; then
        jobs[${#jobs[@]}]=$j
    fi
done
if [[ "$jobs" ]]; then
    joblist=$(printf "%s," ${jobs[@]})
fi
echo "$(TZ=UTC date +%Y-%m-%dT%H:%M:%S.%N) Prolog - current list of active jobs on this node - ${joblist%,}"
if [[ -w /sys/kernel/mOS/ras/jobid ]]; then
    echo -n ${joblist%,} > /sys/kernel/mOS/ras/jobid
    echo "$(TZ=UTC date +%Y-%m-%dT%H:%M:%S.%N) Prolog - updated the mOS repository (/sys/kernel/mOS/ras/jobid) with the list of active jobs on this node"
else
    echo "$(TZ=UTC date +%Y-%m-%dT%H:%M:%S.%N) Prolog - file /sys/kernel/mOS/ras/jobid does not exist, so I could not put the list of active jobs into the mOS repository!"
fi
#
echo "$(TZ=UTC date +%Y-%m-%dT%H:%M:%S.%N) Prolog - ended"
exit $result
